[package]
name = "vst3-rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
itertools = "0.10.3"
widestring = "0.4.0"
vst3-sys = { path = "../vst3-sys" }
vst3-com = { path = "../vst3-sys/com" }
